export type BillboardFormData = {
  billboardName: string;
  market: string;
  vendor: string;
  mediaType: string;
  unitNumber: string;
  tabId: string;
  numberOfUnits: number;
  description: string;
  face: string;
  size: string;
  pixels: string;
  illuminated: boolean;
  weeklyEOIs: number;
  fourWeekImp: number;
  latitude: number;
  longitude: number;
  availableTiming?: string;
  fourWeekRateCard: number;
  fourWeekNegotiatedCost: number;
  installsIncluded?: number;
  additionalInstallCost?: number;
  productionCost?: number;
  shippingAddress?: string;
  artworkDeadline?: string;
  ownerId: number;
};
export type OwnerData = {
  name: string;
  email: string;
};

export type BillboardData = {
  id: 2;
  billboardName: string;
  market: string;
  vendor: string;
  mediaType: string;
  unitNumber: string;
  tabId: null | number;
  description: string;
  face: string;
  sizeX: string;
  sizeY: string;
  pixels: string | null;
  illuminated: null | boolean;
  weeklyEOIs: null | number;
  fourWeekImp: null | number;
  latitude: number;
  longitude: number;
  availableTiming: string;
  fourWeekRateCard: null | string;
  fourWeekNegotiatedCost: null | string;
  installsIncluded: null | string;
  additionalInstallCost: null | string;
  productionCost: null | string;
  shippingAddress: null | string;
  artworkDeadline: null | string;
  dateCreated: string;
  ownerId: number;
};
